---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install the aodh components
  hosts: aodh_all
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - name: Use the lxc-openstack aa profile
      lxc_container:
        name: "{{ container_name }}"
        container_config:
          - "lxc.aa_profile=lxc-openstack"
      register: container_config
      delegate_to: "{{ physical_host }}"
      when: not is_metal | bool
      tags:
        - lxc-aa-profile
    - name: Wait for container ssh
      wait_for:
        port: "22"
        delay: "{{ ssh_delay }}"
        search_regex: "OpenSSH"
        host: "{{ ansible_ssh_host }}"
      delegate_to: "{{ physical_host }}"
      when: container_config is defined and container_config | changed
      register: ssh_wait_check
      until: ssh_wait_check | success
      retries: 3
      tags:
        - ssh-wait
    - name: Sort the rabbitmq servers
      dist_sort:
        value_to_lookup: "{{ container_name }}"
        ref_list: "{{ groups['aodh_all'] }}"
        src_list: "{{ rabbitmq_servers }}"
      register: servers
      tags:
        - always
    - name: Set rabbitmq servers
      set_fact:
        rabbitmq_servers: "{{ servers.sorted_list }}"
      tags:
        - always
    - name: Create log dir
      file:
        path: "{{ item.path }}"
        state: directory
      with_items:
        - { path: "/openstack/log/{{ inventory_hostname }}-aodh" }
      when: is_metal | bool
      tags:
        - aodh-logs
        - aodh-log-dirs
    - name: Ensure Rabbitmq vhost
      rabbitmq_vhost:
        name: "{{ aodh_rabbitmq_vhost }}"
        state: "present"
      delegate_to: "{{ groups['rabbitmq_all'][0] }}"
      when:
        - inventory_hostname == groups['aodh_api'][0]
        - groups['rabbitmq_all']|length > 0
      tags:
        - aodh-rabbitmq
        - aodh-rabbitmq-vhost
    - name: Ensure rabbitmq user
      rabbitmq_user:
        user: "{{ aodh_rabbitmq_userid }}"
        password: "{{ aodh_rabbitmq_password }}"
        vhost: "{{ aodh_rabbitmq_vhost }}"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
        state: "present"
      delegate_to: "{{ groups['rabbitmq_all'][0] }}"
      when:
        - inventory_hostname == groups['aodh_api'][0]
        - groups['rabbitmq_all']|length > 0
      tags:
        - aodh-rabbitmq
        - aodh-rabbitmq-user
    - name: Create DB for service
      mysql_db:
        login_user: "{{ galera_root_user }}"
        login_password: "{{ galera_root_password }}"
        login_host: "{{ aodh_galera_address }}"
        name: "{{ aodh_galera_database }}"
        state: "present"
      when: inventory_hostname == groups['aodh_all'][0]
      delegate_to: "{{ groups['galera_all'][0] }}"
      tags:
        - mysql-db-setup
    - name: Grant access to the DB for the service
      mysql_user:
        login_user: "{{ galera_root_user }}"
        login_password: "{{ galera_root_password }}"
        login_host: "{{ aodh_galera_address }}"
        name: "{{ aodh_galera_user }}"
        password: "{{ aodh_container_db_password }}"
        host: "{{ item }}"
        state: "present"
        priv: "{{ aodh_galera_database }}.*:ALL"
      when: inventory_hostname == groups['aodh_all'][0]
      delegate_to: "{{ groups['galera_all'][0] }}"
      with_items:
        - "localhost"
        - "%"
      tags:
        - mysql-db-setup
  roles:
    - role: "os_aodh"
      aodh_venv_tag: "{{ openstack_release }}"
      aodh_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/aodh-{{ openstack_release }}.tgz"
      tags:
        - "os-aodh"
    - { role: "openstack_openrc", tags: [ "openstack-openrc" ] }
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: aodh_log_rotate
      rsyslog_client_log_dir: "/var/log/aodh"
      rsyslog_client_config_name: "99-aodh-rsyslog-client.conf"
      tags:
        - "aodh-rsyslog-client"
  post_tasks:
    - name: Ensure uwsgi directories exist
      file: path={{ item }} state=directory mode=0771
      with_items:
            - '/etc/uwsgi/'
            - '/etc/uwsgi/wsgi'
    - name: Ensure system package dependencies for uwsgi
      apt: pkg={{ item }}
      with_items:
        - build-essential
        - python-dev
    - name: Install uwsgi server
      pip: name=uwsgi virtualenv='/openstack/venvs/uwsgi'
    - name: Apply service wsgi configuration
      file: src={{ uwsgi_wsgi_file }} dest=/etc/uwsgi/wsgi/{{ uwsgi_service_name }}.wsgi state=link
    - name: Apply wsgi configuration
      copy: src='files/{{ uwsgi_config_file }}' dest='/etc/uwsgi/{{ uwsgi_config_file }}' mode=0774
    - name: Apply upstart configuration for uwsgi
      template: src='files/uwsgi_upstart.conf.j2' dest='/etc/init/uwsgi.conf' mode=0770
    - name: Ensure uwsgi service started
      service: name=uwsgi state=restarted

  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
    aodh_rabbitmq_userid: aodh
    aodh_rabbitmq_vhost: /aodh
    aodh_rabbitmq_servers: "{{ rabbitmq_servers }}"
    aodh_rabbitmq_port: "{{ rabbitmq_port }}"
    aodh_rabbitmq_use_ssl: "{{ rabbitmq_use_ssl }}"
    pip_lock_to_internal_repo: "{{ (pip_links | length) >= 1 }}"
    uwsgi_service_name: aodh
    uwsgi_wsgi_file: '/openstack/venvs/aodh-master/lib/python2.7/site-packages/aodh/api/app.wsgi'
    uwsgi_config_file: 'aodh-uwsgi.ini'
